=pod

=head1 NAME

Getopt::Guided - getopts implementation that follows POSIX utility guidelines

=head1 SYNOPSIS

  use Getopt::Guided qw( getopts );

  local @ARGV = qw( -c -a foo );
  my %opts = ( d => 'bar' );
  getopts 'a:bcd:', %opts;

=head1 DESCRIPTION

This module reimplements the C<getopts()> function of the L<Getopts::Std>
core module.  The new implementation supports only the two-parameter
form of C<getopts()>.  The first parameter is a string that contains the
option characters.  The second parameter is a hash reference that stores
the processing result. Each hash key refers to a provided option character
and the corresponding hash value refers to the option-argument (or C<1>
if it is a flag). This module exports the C<getopts()> function on request.

The new implementation follows the L<POSIX utility syntax
guidelines|https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02>
4 to 10, inclusive. C<getopts()> dies if a processing error occurs; otherwise
the function returns nothing (void context). The processing errors are:

=over 2

=item * illegal option

=item * option requires an argument

=item * option with argument isn't last one in group

=head1 CAVEAT

Even if you are currently using the two-parameter form of the C<getopts()>
function of C<Getopts::Std>, the new implementation isn't a drop in
replacement.

=back

=head1 AUTHOR

Sven Willenbuecher <sven.willenbuecher@gmx.de>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2025 by Sven Willenbuecher.

This is free software; you can redistribute it and/or modify it under the
same terms as the Perl 5 programming language system itself.

=cut


# https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html
#https://stackoverflow.com/questions/56131811/is-there-a-tacit-list-of-reserved-names-for-posix-short-options

# - One or more options without option-arguments, followed by at most one option that takes an option-argument, should be accepted when grouped behind one '-' delimiter.
# https://stackoverflow.com/questions/26542155/getopt-accepting-other-option-as-argument-in-c
# - Each option and option-argument should be a separate argument

# - The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the '-' character.

# - All options should precede operands on the command line.

